pipeline:
  name: test-signal
  identifier: testsignal
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: Signal-Android
        build: <+input>
  stages:
    - stage:
        name: android
        identifier: android
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Validate Gradle Wrapper
                  identifier: Validate_Gradle_Wrapper
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    settings:
                      uses: gradle/wrapper-validation-action@v1
