pipeline:
  name: test-signal-public-release
  identifier: testsignalpublicrelease
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: signal-android
        build: <+input>
  stages:
    - stage:
        name: Builds
        identifier: Builds
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: hello
                  identifier: hello
                  spec:
                    shell: Sh
                    command: echo "hello"
