pipeline:
  name: test-signal-buildjet
  identifier: testsignalbuildjet
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: test-signal
        build: <+input>
  stages:
    - stage:
        name: docker
        identifier: docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build image
                  identifier: Build_image
                  spec:
                    shell: Sh
                    command: cd reproducible-builds && docker build -t signal-android . && cd ..
              - step:
                  type: Run
                  name: Test build
                  identifier: Test_build
                  spec:
                    shell: Sh
                    command: docker run --rm -v $(pwd):/project -w /project signal-android ./gradlew clean assemblePlayProdRelease
    - stage:
        name: android
        identifier: android
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Validate Gradle Wrapper
                  identifier: validate_gradle_wrapper
                  spec:
                    shell: Sh
                    command: ./gradlew wrapper
              - step:
                  type: Run
                  name: Build with Gradle
                  identifier: Build_with_Gradle
                  spec:
                    shell: Sh
                    command: ./gradlew qa
                  when:
                    stageStatus: All
                  failureStrategies: []
  allowStageExecutions: true
